spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
  datasource:
    username: root
    password: 970622
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.233.28:3306/my_blog_site?useSSL=false&serverTimeZone=UTC&characterEncoding=utf-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop