spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
  datasource:
    username: root
    password: 970622
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.233.28:3306/blog?useSSL=false&serverTimeZone=UTC&characterEncoding=utf-8
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
#    open-in-view: false 设为false不能头像上传
file:
  server:
    url: http://localhost:8081/upload